apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - promotion-task.yaml
  - warehouse.yaml
  - staging.yaml
  - production.yaml
generators:
  - github-creds-generator.yaml
